
- name: docker build and push
  hosts: JenkinsSonarServer  # Replace with the hostname or IP address of your target server
  become: yes  # Run tasks with sudo privileges

  tasks:
    - name: Update apt package cache
      apt:
        update_cache: yes

    - name: Build Docker Image
      command: docker build -t PETSHOP .
      args:
        chdir: /var/lib/jenkins/workspace/PETSHOP

    - name: tag image
      command: docker tag PETSHOP:latest gabin75/PETSHOP:latest

    - name: Log in to Docker Hub
      community.docker.docker_login:
        registry_url: https://index.docker.io/v1/
        username: gabin75
        password: dckr_pat_FW1haXYIM6DNLq5SrCEQgoQTXCo

    - name: Push image
      command: docker push gabin75/PETSHOP:latest

    - name: Run container
      command: docker run -d --name pet1 -p 8081:8080 gabin75/PETSHOP:latest
